apiVersion: apps/v1
kind: Deployment
metadata:
  name: gegegator
  namespace: gegerator
  labels:
    app: gegerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gegerator
  template:
    metadata:
      labels:
        app: gegerator
    spec:
      containers:
        - name: gegerator
          image: bsiri/gegerator:1.0.1-SNAPSHOT
          ports:
            - name: gegerator-port
              containerPort: 8080
