apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gegerator
  namespace: gegerator
spec:
  ingressClassName: nginx
  rules:
    - host: gegerator.minikube.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gegerator
                port:
                  name: gegerator-port