apiVersion: v1
kind: Service
metadata:
  name: gegerator
  namespace: gegerator
spec:
  type: ClusterIP
  selector:
    app: gegerator
  ports:
    - name: gegerator-port
      protocol: TCP
      port: 8080
      targetPort: gegerator-port
