apiVersion: v2
name: gegerator
type: application
version: "1.0.1-SNAPSHOT"
appVersion: "1.0.1-SNAPSHOT"
description: Gegerateur est un outil d'aide Ã  la plannification de planning de films pour les festivaliers du Festival de films fantastiques de Gerardmer.

maintainers:
  - name: bsiri
home: "https://github.com/bsiri/gegerator"
sources:
  - "https://github.com/bsiri/gegerator"
